// Generated by CoffeeScript 1.8.0
(function() {
  var Application,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Application = (function() {
    function Application() {
      this.pause = __bind(this.pause, this);
      this.download = __bind(this.download, this);
      this.downloadMan = new DownloadManager();
      this.opts = {
        image: {
          height: 100,
          width: 200,
          margin: 20
        }
      };
      $('#downloadButton').on('click', this.download);
      $('#pauseButton').on('click', this.pause);
      this.flag = 'unpaused';
    }

    Application.prototype.fetchImages = function(filterTags, onDone) {
      var data, fetching;
      data = {
        page: 1,
        imgs_per_page: 15000,
        filter_tags: JSON.stringify(filterTags),
        mode: 'share_link',
        share_link: this.shareLinkCode
      };
      fetching = this.apiCall('/images/load/', data);
      return fetching.done(onDone);
    };

    Application.prototype.download = function() {
      var imgNode, loadingIntoLocal, num, url, urls, _i, _ref, _results;
      urls = ['http://demo.zvezdochka.io/aMG_6668.jpg', 'http://demo.zvezdochka.io/aMG_6648.jpg', 'http://demo.zvezdochka.io/DSC_0313.jpg', 'http://demo.zvezdochka.io/IMG_6671.jpg', 'http://demo.zvezdochka.io/DSC_1092.jpg', 'http://demo.zvezdochka.io/aMG_6652.jpg', 'http://demo.zvezdochka.io/aMG_6719.jpg', 'http://demo.zvezdochka.io/DSC_0296.jpg', 'http://demo.zvezdochka.io/DSC_0312.jpg', 'http://demo.zvezdochka.io/aMG_6675.jpg', 'http://demo.zvezdochka.io/DSC_0957.jpg', 'http://demo.zvezdochka.io/aMG_6716.jpg', 'http://demo.zvezdochka.io/DSC_0970.jpg', 'http://demo.zvezdochka.io/aSC_1093.jpg', 'http://demo.zvezdochka.io/DSC_1091.jpg', 'http://demo.zvezdochka.io/DSC_0956.jpg', 'http://demo.zvezdochka.io/DSC_0123.jpg', 'http://demo.zvezdochka.io/IMG_6712.jpg'];
      _results = [];
      for (num = _i = 0, _ref = urls.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; num = 0 <= _ref ? ++_i : --_i) {
        url = urls[num] + '?' + (+new Date());
        imgNode = ($('<div>')).addClass('item' + num).html('batch #' + Math.floor(num / 3)).append($('<div>').addClass('percentBox'));
        $('body').append(imgNode);
        loadingIntoLocal = this.downloadMan.addTask(url);
        _results.push((function(imgNode) {
          loadingIntoLocal.done(function(imgBlobUrl) {
            imgNode.css({
              backgroundImage: 'url(' + imgBlobUrl + ')'
            });
            return imgNode.html('');
          });
          return loadingIntoLocal.progress(function(percentComplete) {
            return $('.percentBox', imgNode).html(percentComplete + '%');
          });
        })(imgNode));
      }
      return _results;
    };

    Application.prototype.pause = function() {
      if (this.flag === 'unpaused') {
        this.downloadMan.pause();
        $('#pauseButton').html('Возобновить');
        return this.flag = 'paused';
      } else {
        this.downloadMan.resume();
        $('#pauseButton').html('Поставить на паузу');
        return this.flag = 'unpaused';
      }
    };

    window.Application = Application;

    return Application;

  })();

}).call(this);
